apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: deezicypher/auth
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_AUTH_DB
            - name: ACTIVE_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ACTIVE_TOKEN_SECRET
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: REFRESH_TOKEN_SECRET
            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: CLIENT_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: AUTH_NODE_ENV
            

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000


