apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-postgres
  template:
    metadata:
      labels:
        app: tickets-postgres
    spec:
      containers:
        - name: tickets-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_TICKETS_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts: 
            - name: postgres-storage
              mountPath: /var/lib/postgresql/tickets_data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim: 
            claimName: tickets-postgres-pvc  



---
apiVersion: v1
kind: Service
metadata:
  name: tickets-postgres-srv
spec:
  selector:
    app: tickets-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tickets-postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tickets-postgres-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi