name: tests-auth

on: 
    pull_request
jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: auth_test
                ports:
                - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - uses: actions/checkout@v4
            - run: cd auth && npm install && npm run test:ci
              env:
                DATABASE_URL: ${{ secrets.DATABASE_URL }}
                NODE_ENV: dev