name: tests-tickets

on: 
    pull_request
jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: auth_test
                ports:
                - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - uses: actions/checkout@v4
            - run: cd tickets && npm install && npm run test:ci
              env:
                DATABASE_URL: postgres://postgres:postgres@localhost:5432/auth_test
                NODE_ENV: test